### ISSUE TITLE
error

### ISSUE THREAD

**Issue by whiteysy** [named-data/mini-ndn#26]
Hi,
It occurs some error when i start minindn-wifi and minindn works well. Please help me.

ysy@ysy-ubuntu:/home/minindn-wifi$ sudo minindn --wifi --adhoc
Parse of /usr/local/etc/mini-ndn/wifi/adhoc-topology.conf done.
*** Creating adhoc network
*** Adding controller
c0
*** Adding hosts and stations:
sta1 sta2 sta3 sta4 
*** Configuring propagation model...

*** Configuring wifi nodes...
Traceback (most recent call last):
  File "/usr/local/bin/minindn", line 4, in <module>
    __import__('pkg_resources').run_script('MiniNDN-WiFi==0.1.0', 'minindn')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/MiniNDN_WiFi-0.1.0-py2.7.egg/EGG-INFO/scripts/minindn", line 616, in <module>
    execute(options)
  File "/usr/local/lib/python2.7/dist-packages/MiniNDN_WiFi-0.1.0-py2.7.egg/EGG-INFO/scripts/minindn", line 464, in execute
    options.ctime, options.nPings, options.pctTraffic, options.experimentName, options.nlsrSecurity)
  File "/usr/local/lib/python2.7/dist-packages/MiniNDN_WiFi-0.1.0-py2.7.egg/ndnwifi/ndnadhoc.py", line 119, in build_adhocnet
    adhocnet.configureWifiNodes()
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.0d1-py2.7.egg/mininet/net.py", line 788, in configureWifiNodes
    self.stations, self.aps = mininetWiFi.configureWifiNodes(self)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.0d1-py2.7.egg/mininet/wifiNet.py", line 1063, in configureWifiNodes
    cls.configureWirelessLink(mininet.stations, mininet.aps, mininet.cars)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.0d1-py2.7.egg/mininet/wifiNet.py", line 875, in configureWirelessLink
    cls.configureMacAddr(node)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.0d1-py2.7.egg/mininet/wifiNet.py", line 1037, in configureMacAddr
    node.params['mac'][wlan] = node.getMAC(iface)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.0d1-py2.7.egg/mininet/node.py", line 276, in getMAC
    debug('%s\n' % mac[0])
IndexError: list index out of range

**Comment by agawande** [comment]
Where are you using the minindn-wifi from?
Probably better to post on: https://github.com/iamxg/minindn-wifi

**Comment by whiteysy** [comment]
OK,thanks a lot !
