### ISSUE TITLE
NFD question

### ISSUE THREAD

**Issue by whiteysy** [named-data/mini-ndn#30]
Hi,
When NFD works in a wireless network, is there a difference between the wireless network and the wired network on the forwarding mechanism? How do two nodes initially establish a connection at the physical and data link layers? It is based on 802.11 and commuicates by encapsulating the NDN packet into an IP packet in the simulator?
Look forward to your reply!

**Comment by agawande** [comment]
NFD works at the level of faces. A face can be a udp, tcp, or ethernet or any other transport. The Mini-NDN emulator just runs NFD. Currently Mini-NDN does not support wifi interface as Mininet does not support them.
(It might be better to ask such type of questions by joining the relevant mailing list (nfd-dev or mini-ndn): https://named-data.net/codebase/platform/support/mailing-lists/)

**Comment by whiteysy** [comment]
Thank you!

**Comment by whiteysy** [comment]
Hi,
When I look at the source code, I find NLSR sends LSA-interest and LSA-data by faces of ndn-cxx. Does it mean that the interaction between them is specific because of not depending on NFD? 
Look forward to your reply!

**Comment by agawande** [comment]
The ndn-cxx face is how NLSR connects to NFD. All Interests and Data do go through NFD.

**Comment by whiteysy** [comment]
After I reinstall the lasted version of minindn, it can not work and has some error.
ysy@ysy-ThinkCentre-E75:~/mini-ndn$ sudo minindn
Traceback (most recent call last):
  File "/usr/local/bin/minindn", line 4, in <module>
    __import__('pkg_resources').run_script('Mini-NDN==0.4.0', 'minindn')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/Mini_NDN-0.4.0-py3.5.egg/EGG-INFO/scripts/minindn", line 70, in <module>
    from ndn import ExperimentManager
  File "/usr/local/lib/python3.5/dist-packages/Mini_NDN-0.4.0-py3.5.egg/ndn/__init__.py", line 24, in <module>
    import experiment_manager as ExperimentManager
ImportError: No module named 'experiment_manager'

**Comment by agawande** [comment]
Can you try with python2? I think python3.5 might be causing problems.

**Comment by whiteysy** [comment]
Thanks for your reply, but it still has some problems after I use python 2.7. It can not get the mininet module. And it is caused by the version of the mininet?
Traceback (most recent call last):
  File "/usr/local/bin/minindn", line 4, in <module>
    __import__('pkg_resources').run_script('Mini-NDN==0.4.0', 'minindn')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/Mini_NDN-0.4.0-py2.7.egg/EGG-INFO/scripts/minindn", line 61, in <module>
    from mininet.topo import Topo
ImportError: No module named mininet.topo

**Comment by agawande** [comment]
Does mininet work:
sudo mn
?
How did you install Mininet? Should be from source.

**Comment by whiteysy** [comment]
Thank you for your reply! 
I have solved it. The problem is due to incorrect mininet version.
