### ISSUE TITLE
Module Not Found- miniNDN

### ISSUE THREAD

**Issue by sqb39** [named-data/mini-ndn#37]
I just installed minindn and all its dependencies following the instructions in GitHub. After installing, when I write the command: "sudo minindn" the following error occurs:

**Traceback (most recent call last):
  File "/usr/local/bin/minindn", line 4, in <module>
    __import__('pkg_resources').run_script('Mini-NDN==0.4.0', 'minindn')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/Mini_NDN-0.4.0-py3.6.egg/EGG-INFO/scripts/minindn", line 70, in <module>
    from ndn import ExperimentManager
  File "/usr/local/lib/python3.6/dist-packages/Mini_NDN-0.4.0-py3.6.egg/ndn/__init__.py", line 24, in <module>
    import experiment_manager as ExperimentManager
ModuleNotFoundError: No module named 'experiment_manager'**

FYI, my mininet is running properly

**Comment by RafaelDBeltran** [comment]
Hey, i do have the same problem and solve. In my case this happen because my S.O is not present on list of install of the mininet in the setup script and the script install on the python priority(my case python2.7). I edit the scripts to be compatible with my machine. After that i install the infoedit again and it worked.
