### ISSUE TITLE
examples/nlsr/pingall.py fails

### ISSUE THREAD

**Issue by nikosft** [named-data/mini-ndn#54]
This script fails with the following error

```
Traceback (most recent call last):
  File "examples/nlsr/pingall.py", line 56, in <module>
    Experiment.startPctPings(ndn.net, args.nPings, args.pctTraffic)
  File "/home/mmlab/mini-ndn/minindn/helpers/experiment.py", line 98, in startPctPings
    NDNPingClient.ping(host, other, nPings)
  File "/home/mmlab/mini-ndn/minindn/helpers/ndnpingclient.py", line 45, in ping
    str.replace(prefix[1:], "/", "-")
```

line #98 of `mini-ndn/minindn/helpers/experiment.py` should be replaced from `NDNPingClient.ping(host, other, nPings)` to `NDNPingClient.ping(host, other.name, nPings)`

**Comment by Jiacheng98** [comment]
Thanks!!!
