### ISSUE TITLE
Module Not Found Error : experiment_manager

### ISSUE THREAD

**Issue by renirss** [named-data/mini-ndn#76]
Hi everyone, 

I just finish installed minindn and follow the instruction. When i try to using command "sudo minindn" the following error occurs:

Traceback (most recent call last):
  File "/usr/local/bin/minindn", line 4, in <module>
	__import__('pkg_resources').run_script('Mini-NDN==0.3.0', 'minindn')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
	self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1463, in run_script
	exec(code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/Mini_NDN-0.3.0-py3.8.egg/EGG-INFO/scripts/minindn", line 71, in <module>
	from ndn import ExperimentManager
  File "/usr/local/lib/python3.8/dist-packages/Mini_NDN-0.3.0-py3.8.egg/ndn/__init__.py", line 24, in <module>
	import experiment_manager as ExperimentManager
ModuleNotFoundError: No module named 'experiment_manager'

has anyone get the same problem and already solved? 

thanks a lot

**Comment by dulalsaurab** [comment]
The `sudo minindn` command no longer exists. Instead, you can write an experiment script and run it using the following command: "sudo python <minindn-script.py>".

Please refer to the latest documentation (https://minindn.memphis.edu/experiment.html) for more detailed information.

**Comment by renirss** [comment]
okay, thank you for the answer 🙏
